### PR TITLE
Composer: allow Symfony 5

### PR DESCRIPTION
**Pull request by bretrzaun**
This change allows to use this bundle with Symfony 5.

### CODE REVIEW

**Comment by mpdude** [comment]
If there are no other changes required, 🎉

Can we do this without changing the package name or bumping PHP requirements?

**Comment by bretrzaun** [comment]
I tested it with a newly created Symfony 5 application - no problems so far.
Since the old Symfony versions are still allowed no PHP version bumping needed.

**Comment by mpdude** [comment]
So could you update this PR please?

**Comment by bretrzaun** [comment]
Sorry, I just noticed I created the PR from the wrong branch. Will delete and recreate...

**Pull request closed without merging**
