### PR TITLE
Symfony 4 compatibility

### PR DESCRIPTION
**Pull request by BernhardWebstudio**
Relevant changes:

- upgrades of the dependencies
- removal of dependency on symfony/symfony as this dependency [broke](http://symfony.com/doc/current/setup/flex.html#upgrading-existing-applications-to-flex) the compatibility with flex 
- added the relevant dependencies for this Bundle
- fixed Unit-Tests to work and run without problems with the upgraded version of phpunit

### CODE REVIEW

**Comment by BernhardWebstudio** [comment]
The PHP jump should not be a problem as it is specified as a requirement. Composer should therefore handle it if the user has not yet the correct PHP version, and will just load the former version of this bundle. Users without this PHP 7.1 cannot use Symfony 4, and therefore do not care about this update anyway. Or did I understand something wrong?

**Comment by mpdude** [comment]
What I wanted to say is that if we release a 2.5 with a requirement of at least Symfony 3.0 and PHP 7, we cannot ship features for Symfony 2/PHP 5 users anymore – and Symfony 2.8 is still under maintenance.

Anyways, given the rate of feature additions I think we can neglect this.

Could you please nod, @MalteWunsch?

**Comment by MalteWunsch** [comment]
Sorry for the delay.

Good point, @mpdude. In this case, the minor bump is okay with me. Even Symfony 2.8 doesn't get any new features, but only bug fixes until this November and security fixes for another year. We can provide both bug fixes and security fixes with an increased patch version of the piwik-bundle, so there'll be no collision. In general, the answer might differ, but that's a topic for another day. I'll merge and tag.

**Comment by MalteWunsch** [comment]
Thank you, @BernhardWebstudio !

**Pull request merged**
