### PR TITLE
Noscript element and more parameters

### PR DESCRIPTION
**Pull request by relthyg**
Adds the `<noscript>`-element and the parameters `"setDoNotTrack", true`, `"trackPageView"` and `"enableLinkTracking"` to the tracking code.

### CODE REVIEW

**Comment by mpdude** [comment]
I'd be fine with this, even if it is (from a strict point of view) a possibly behaviour-changing commit.

Do you think you could fix the Travis tests as well?

**Comment by relthyg** [comment]
Sure. Do you agree that there is no need to support PHP 5.3 anymore?

**Comment by mpdude** [comment]
Sure, I think you can also drop HHVM.

**Comment by mpdude** [comment]
Oh, wait. https://symfony.com/blog/symfony-4-end-of-hhvm-support

Let's keep HHVM on the branch for Symfony 2.x and drop it on the Symfony 3.x branch.

**Comment by TomaszGasior** [comment]
Will be this PR ported into 2.5 version?

**Comment by relthyg** [comment]
Meanwhile, it is.

**Pull request merged**
